export const PRODUCTS = [
    {
        id: 'pulseira',
        name: 'Pulseira Bruna Mandz',
        description:
            'Pulseira exclusiva com identidade Bruna Mandz. Acessório perfeito para mostrar que você faz parte da escola.',
        price: 19.9,
        stock: 80,
        active: true,
        category: 'acessorios',
        badge: 'Novidade',
        badgeColor: 'green',
        image: '/Pulseira.png',
        rewardXp: 20,
        variants: null,
    },
    {
        id: 'palheta',
        name: 'Palheta Personalizada',
        description:
            'Palheta personalizada com a logo Bruna Mandz. Item essencial para guitarristas e violonistas da escola.',
        price: 9.9,
        stock: 150,
        active: true,
        category: 'acessorios',
        badge: null,
        image: '/Paleta.png',
        rewardXp: 10,
        variants: null,
    },
    {
        id: 'chaveiro',
        name: 'Chaveiro Bruna Mandz',
        description:
            'Chaveiro com arte exclusiva da escola. Pequeno, resistente e cheio de personalidade musical.',
        price: 14.9,
        stock: 100,
        active: true,
        category: 'acessorios',
        badge: null,
        image: '/Chaveiro.png',
        rewardXp: 15,
        variants: null,
    },
    {
        id: 'copo-termico',
        name: 'Copo Térmico Bruna Mandz',
        description:
            'Copo térmico com logo da escola. Mantém sua bebida na temperatura certa durante horas de estudo e ensaio.',
        price: 59.9,
        stock: 30,
        active: true,
        category: 'acessorios',
        badge: 'Premium',
        badgeColor: 'yellow',
        image: '/Copo.png',
        rewardXp: 60,
        variants: null,
    },
    {
        id: 'camisa-classica',
        name: 'Camisa Clássica',
        description:
            'A camisa oficial da escola. 100% algodão, confortável e com o design clássico Bruna Mandz — perfeita para o dia a dia.',
        price: 69.9,
        stock: 50,
        active: true,
        category: 'roupas',
        badge: 'Mais Vendida',
        badgeColor: 'red',
        image: '/TSHIRT_PREMIUN.png',
        rewardXp: 70,
        variants: {
            sizes: ['P', 'M', 'G', 'GG'],
        },
    },
    {
        id: 'camisa-minimalista',
        name: 'Camisa Minimalista',
        description:
            'Design limpo e moderno. Para quem prefere um visual mais sutil mas ainda quer carregar a identidade da escola.',
        price: 69.9,
        stock: 50,
        active: true,
        category: 'roupas',
        badge: null,
        image: '/TSHIRT_PRO.png',
        rewardXp: 70,
        variants: {
            sizes: ['P', 'M', 'G', 'GG'],
        },
    },
    {
        id: 'camisa-rock',
        name: 'Camisa Rock',
        description:
            'Para os que vivem o rock. Arte exclusiva com pegada pesada e muito estilo — feita para quem toca com a alma.',
        price: 69.9,
        stock: 50,
        active: true,
        category: 'roupas',
        badge: 'Exclusiva',
        badgeColor: 'purple',
        image: '/TSHIRT_ROCK.png',
        rewardXp: 70,
        variants: {
            sizes: ['P', 'M', 'G', 'GG'],
        },
    },
];
