export const PRODUCTS = [
    {
        id: 'camisa-nposso',
        name: 'Camisa "Não Posso, Tenho Ensaio"',
        description: 'Camisa com estampa clássica "Não Posso, Tenho Ensaio". Perfeita para ensaios e para o dia a dia.',
        price: 69.90,
        stock: 50,
        active: true,
        category: 'roupas',
        badge: 'Novidade',
        badgeColor: 'purple',
        image: '/products/NPOSSO.jpeg',
        variants: {
            sizes: ['P', 'M', 'G', 'GG'],
        },
    },
    {
        id: 'camisa-padrao',
        name: 'Camisa Oficial Padrão',
        description: 'A camisa oficial com design premium da escola Bruna Mandz.',
        price: 69.90,
        stock: 50,
        active: true,
        category: 'roupas',
        badge: 'Promoção',
        badgeColor: 'green',
        image: '/products/PADRAO.jpeg',
        variants: {
            sizes: ['P', 'M', 'G', 'GG'],
        },
    },
    {
        id: 'suporte-baqueta',
        name: 'Suporte de Baqueta',
        description: 'Suporte organizador de baquetas para bateria. Prático e resistente.',
        price: 49.90,
        stock: 30,
        active: true,
        category: 'acessorios',
        badge: 'Limitado',
        badgeColor: 'orange',
        image: '/products/baqueta.png',
        variants: null,
    },
];
